# This is the Run ModelSim file list for 'final_project_txrx_fp_Phase_extraction_and_synchronization'

vcom -93 -quiet $base_dir/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
vcom -93 -quiet $base_dir/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
vcom -93 -quiet $base_dir/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
vcom -93 -quiet $base_dir/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
source $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Zki026142iyc5.dspb.do
source $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zp06o303d0doz.dspb.do
source $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zp06o303d0doz.dspb.do
source $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zp06o303d0doz.dspb.do
source $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zp06o303d0doz.dspb.do
source $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA2Zp06o303d0doz.dspb.do
source $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA2Zp06o303d0doz.dspb.do
source $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_subBloA0Z4004ki02975u.dspb.do
source $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_subBloA0Z4004ki02975u.dspb.do
source $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Zk614004kii5u.dspb.do
source $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Zk614004kii5u.dspb.do
