# This is the Quartus file list for 'final_project_txrx_fp_Phase_extraction_and_synchronization'

set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
source C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Zki026142iyc5.add.tcl
source C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zp06o303d0doz.add.tcl
source C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zp06o303d0doz.add.tcl
source C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zp06o303d0doz.add.tcl
source C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zp06o303d0doz.add.tcl
source C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA2Zp06o303d0doz.add.tcl
source C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA2Zp06o303d0doz.add.tcl
source C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_subBloA0Z4004ki02975u.add.tcl
source C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_subBloA0Z4004ki02975u.add.tcl
source C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Zk614004kii5u.add.tcl
source C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Zk614004kii5u.add.tcl
