# This is the Quartus file list for 'floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z0m6140i0k614004kii5u'

set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
