# This is the Run ModelSim file list for 'floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_modBloA0Z03p06o303d06o00rf30z'

vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_modBloA0Z6o303d06o00rf30z.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_modBloA0Z6o303d06o00rf30z.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_modBloA0Z6o303d06o00rf30z.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_modBloA0Z6o303d06o00rf30z.vhd
