# This is the Run ModelSim file list for 'floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z0m6140i0k614004kii5u'

vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_arcTanA0Z40i0k614004kii5u.vhd
