# This is the Quartus file list for 'floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Z0k614004ki026142iyc5'

set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Z4004ki026142iyc5.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Z4004ki026142iyc5.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Z4004ki026142iyc5.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Z4004ki026142iyc5.vhd
