# This is the Quartus file list for 'floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zcp06of03p06o303d0doz'

set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zof03p06o303d0doz.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zof03p06o303d0doz.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zof03p06o303d0doz.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zof03p06o303d0doz.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zof03p06o303d0doz.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zof03p06o303d0doz.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zof03p06o303d0doz.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA0Zof03p06o303d0doz.vhd
