# This is the Quartus file list for 'floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_modBloA0Z03p06o303d06o00rf30z'

set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_modBloA0Z6o303d06o00rf30z.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_modBloA0Z6o303d06o00rf30z.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_modBloA0Z6o303d06o00rf30z.vhd
set_global_assignment -name VHDL_FILE C:/git_projects/MCC150/./rtl/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_modBloA0Z6o303d06o00rf30z.vhd
