# This is the Run ModelSim file list for 'floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Z0k614004ki026142iyc5'

vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Z4004ki026142iyc5.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Z4004ki026142iyc5.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Z4004ki026142iyc5.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_addBloA0Z4004ki026142iyc5.vhd
