# This is the Run ModelSim file list for 'floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zcp06of03p06o303d0doz'

vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zof03p06o303d0doz.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zof03p06o303d0doz.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zof03p06o303d0doz.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zof03p06o303d0doz.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zof03p06o303d0doz.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zof03p06o303d0doz.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zof03p06o303d0doz.vhd
vcom -93 -quiet $base_dir/final_project/floatComponent_final_project_txrx_fp_Phase_extraction_and_synchronization_castBlA1Zof03p06o303d0doz.vhd
