# This is the hw.tcl file for 'final_project_txrx_fp'
# Generated by High Level Design Compiler for Intel(R) FPGAs 

package require -exact qsys 14.1

# module final_project_txrx_fp
set_module_property NAME final_project_txrx_fp
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Altera DSP Builder Advanced"
set_module_property DISPLAY_NAME final_project_txrx_fp
set_module_property EDITABLE false

# filesets
add_fileset DSPBA_QUARTUS_SYNTH QUARTUS_SYNTH quartus_synth_callback
set_fileset_property DSPBA_QUARTUS_SYNTH TOP_LEVEL final_project_txrx_fp

proc quartus_synth_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "final_project_txrx_fp.vhd" VHDL PATH "final_project_txrx_fp.vhd"
	add_fileset_file "final_project_txrx_fp_8_PSK_Mapper.vhd" VHDL PATH "final_project_txrx_fp_8_PSK_Mapper.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView.vhd" VHDL PATH "final_project_txrx_fp_ChanView.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView1.vhd" VHDL PATH "final_project_txrx_fp_ChanView1.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView2.vhd" VHDL PATH "final_project_txrx_fp_ChanView2.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView3.vhd" VHDL PATH "final_project_txrx_fp_ChanView3.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView4.vhd" VHDL PATH "final_project_txrx_fp_ChanView4.vhd"
	add_fileset_file "final_project_txrx_fp_Decode_symbols_into_bitstream.vhd" VHDL PATH "final_project_txrx_fp_Decode_symbols_into_bitstream.vhd"
	add_fileset_file "final_project_txrx_fp_InterpolatingFIR.vhd" VHDL PATH "final_project_txrx_fp_InterpolatingFIR.vhd"
	add_fileset_file "final_project_txrx_fp_InterpolatingFIR1.vhd" VHDL PATH "final_project_txrx_fp_InterpolatingFIR1.vhd"
	add_fileset_file "final_project_txrx_fp_Memory.vhd" VHDL PATH "final_project_txrx_fp_Memory.vhd"
	add_fileset_file "final_project_txrx_fp_Memory_DualMem.hex" HEX PATH "final_project_txrx_fp_Memory_DualMem.hex"
	add_fileset_file "final_project_txrx_fp_Phase_extraction_and_synchronization.vhd" VHDL PATH "final_project_txrx_fp_Phase_extraction_and_synchronization.vhd"
	add_fileset_file "final_project_txrx_fp_Power_extraction.vhd" VHDL PATH "final_project_txrx_fp_Power_extraction.vhd"
	add_fileset_file "final_project_txrx_fp_Scale.vhd" VHDL PATH "final_project_txrx_fp_Scale.vhd"
	add_fileset_file "final_project_txrx_fp_Scale1.vhd" VHDL PATH "final_project_txrx_fp_Scale1.vhd"
	add_fileset_file "final_project_txrx_fp_Scale2_Q.vhd" VHDL PATH "final_project_txrx_fp_Scale2_Q.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I1.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I1.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I2.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I2.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I3.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I3.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I4.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I4.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I5.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I5.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I6.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I6.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR1.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR1.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR2.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR2.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR_I.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR_I.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR_Q.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR_Q.vhd"
	add_fileset_file "final_project_txrx_fp_Symbol_recovery.vhd" VHDL PATH "final_project_txrx_fp_Symbol_recovery.vhd"
	add_fileset_file "final_project_txrx_fp_Symbol_sample_adaptation.vhd" VHDL PATH "final_project_txrx_fp_Symbol_sample_adaptation.vhd"
}
add_fileset DSPBA_SIM_VERILOG SIM_VERILOG sim_verilog_callback
set_fileset_property DSPBA_SIM_VERILOG TOP_LEVEL final_project_txrx_fp

proc sim_verilog_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "final_project_txrx_fp.vhd" VHDL PATH "final_project_txrx_fp.vhd"
	add_fileset_file "final_project_txrx_fp_8_PSK_Mapper.vhd" VHDL PATH "final_project_txrx_fp_8_PSK_Mapper.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView.vhd" VHDL PATH "final_project_txrx_fp_ChanView.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView1.vhd" VHDL PATH "final_project_txrx_fp_ChanView1.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView2.vhd" VHDL PATH "final_project_txrx_fp_ChanView2.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView3.vhd" VHDL PATH "final_project_txrx_fp_ChanView3.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView4.vhd" VHDL PATH "final_project_txrx_fp_ChanView4.vhd"
	add_fileset_file "final_project_txrx_fp_Decode_symbols_into_bitstream.vhd" VHDL PATH "final_project_txrx_fp_Decode_symbols_into_bitstream.vhd"
	add_fileset_file "final_project_txrx_fp_InterpolatingFIR.vhd" VHDL PATH "final_project_txrx_fp_InterpolatingFIR.vhd"
	add_fileset_file "final_project_txrx_fp_InterpolatingFIR1.vhd" VHDL PATH "final_project_txrx_fp_InterpolatingFIR1.vhd"
	add_fileset_file "final_project_txrx_fp_Memory.vhd" VHDL PATH "final_project_txrx_fp_Memory.vhd"
	add_fileset_file "final_project_txrx_fp_Memory_DualMem.hex" HEX PATH "final_project_txrx_fp_Memory_DualMem.hex"
	add_fileset_file "final_project_txrx_fp_Phase_extraction_and_synchronization.vhd" VHDL PATH "final_project_txrx_fp_Phase_extraction_and_synchronization.vhd"
	add_fileset_file "final_project_txrx_fp_Power_extraction.vhd" VHDL PATH "final_project_txrx_fp_Power_extraction.vhd"
	add_fileset_file "final_project_txrx_fp_Scale.vhd" VHDL PATH "final_project_txrx_fp_Scale.vhd"
	add_fileset_file "final_project_txrx_fp_Scale1.vhd" VHDL PATH "final_project_txrx_fp_Scale1.vhd"
	add_fileset_file "final_project_txrx_fp_Scale2_Q.vhd" VHDL PATH "final_project_txrx_fp_Scale2_Q.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I1.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I1.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I2.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I2.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I3.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I3.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I4.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I4.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I5.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I5.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I6.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I6.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR1.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR1.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR2.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR2.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR_I.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR_I.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR_Q.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR_Q.vhd"
	add_fileset_file "final_project_txrx_fp_Symbol_recovery.vhd" VHDL PATH "final_project_txrx_fp_Symbol_recovery.vhd"
	add_fileset_file "final_project_txrx_fp_Symbol_sample_adaptation.vhd" VHDL PATH "final_project_txrx_fp_Symbol_sample_adaptation.vhd"
}
add_fileset DSPBA_SIM_VHDL SIM_VHDL sim_vhdl_callback
set_fileset_property DSPBA_SIM_VHDL TOP_LEVEL final_project_txrx_fp

proc sim_vhdl_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "final_project_txrx_fp.vhd" VHDL PATH "final_project_txrx_fp.vhd"
	add_fileset_file "final_project_txrx_fp_8_PSK_Mapper.vhd" VHDL PATH "final_project_txrx_fp_8_PSK_Mapper.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView.vhd" VHDL PATH "final_project_txrx_fp_ChanView.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView1.vhd" VHDL PATH "final_project_txrx_fp_ChanView1.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView2.vhd" VHDL PATH "final_project_txrx_fp_ChanView2.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView3.vhd" VHDL PATH "final_project_txrx_fp_ChanView3.vhd"
	add_fileset_file "final_project_txrx_fp_ChanView4.vhd" VHDL PATH "final_project_txrx_fp_ChanView4.vhd"
	add_fileset_file "final_project_txrx_fp_Decode_symbols_into_bitstream.vhd" VHDL PATH "final_project_txrx_fp_Decode_symbols_into_bitstream.vhd"
	add_fileset_file "final_project_txrx_fp_InterpolatingFIR.vhd" VHDL PATH "final_project_txrx_fp_InterpolatingFIR.vhd"
	add_fileset_file "final_project_txrx_fp_InterpolatingFIR1.vhd" VHDL PATH "final_project_txrx_fp_InterpolatingFIR1.vhd"
	add_fileset_file "final_project_txrx_fp_Memory.vhd" VHDL PATH "final_project_txrx_fp_Memory.vhd"
	add_fileset_file "final_project_txrx_fp_Memory_DualMem.hex" HEX PATH "final_project_txrx_fp_Memory_DualMem.hex"
	add_fileset_file "final_project_txrx_fp_Phase_extraction_and_synchronization.vhd" VHDL PATH "final_project_txrx_fp_Phase_extraction_and_synchronization.vhd"
	add_fileset_file "final_project_txrx_fp_Power_extraction.vhd" VHDL PATH "final_project_txrx_fp_Power_extraction.vhd"
	add_fileset_file "final_project_txrx_fp_Scale.vhd" VHDL PATH "final_project_txrx_fp_Scale.vhd"
	add_fileset_file "final_project_txrx_fp_Scale1.vhd" VHDL PATH "final_project_txrx_fp_Scale1.vhd"
	add_fileset_file "final_project_txrx_fp_Scale2_Q.vhd" VHDL PATH "final_project_txrx_fp_Scale2_Q.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I1.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I1.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I2.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I2.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I3.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I3.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I4.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I4.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I5.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I5.vhd"
	add_fileset_file "final_project_txrx_fp_Scale3_I6.vhd" VHDL PATH "final_project_txrx_fp_Scale3_I6.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR1.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR1.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR2.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR2.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR_I.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR_I.vhd"
	add_fileset_file "final_project_txrx_fp_SingleRateFIR_Q.vhd" VHDL PATH "final_project_txrx_fp_SingleRateFIR_Q.vhd"
	add_fileset_file "final_project_txrx_fp_Symbol_recovery.vhd" VHDL PATH "final_project_txrx_fp_Symbol_recovery.vhd"
	add_fileset_file "final_project_txrx_fp_Symbol_sample_adaptation.vhd" VHDL PATH "final_project_txrx_fp_Symbol_sample_adaptation.vhd"
}

# interfaces
# Interface clock
add_interface clock clock end
set_interface_property clock ENABLED true
add_interface_port clock clk clk Input 1
add_interface_port clock areset reset Input 1

# Interface exp
add_interface exp conduit end
set_interface_property exp ENABLED true
add_interface_port exp ADC_I data_ADC_I Input 12
add_interface_port exp ADC_Q data_ADC_Q Input 12
add_interface_port exp rx_bits data_rx_bits Output 1
set_port_property rx_bits VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port exp mem_read_bits data_mem_read_bits Output 1
set_port_property mem_read_bits VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port exp sym_phase data_sym_phase Output 30
add_interface_port exp left_power data_left_power Output 12
add_interface_port exp main_power data_main_power Output 12
add_interface_port exp right_power data_right_power Output 12
add_interface_port exp instant_power_x data_instant_power_x Output 25
