# This is the Quartus file list for 'final_project_txrx_fp_Phase_extraction_and_synchronization'

set_global_assignment -name VHDL_FILE ./rtl/final_project/final_project_txrx_fp_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/final_project/final_project_txrx_fp_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/final_project/final_project_txrx_fp_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/final_project/final_project_txrx_fp_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
set_global_assignment -name VHDL_FILE ./rtl/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
set_global_assignment -name VHDL_FILE ./rtl/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
set_global_assignment -name VHDL_FILE ./rtl/final_project/final_project_txrx_fp_Phase_extraction_and_synchronization.vhd
