# This is the hw.tcl file for 'mp_txrx'
# Generated by High Level Design Compiler for Intel(R) FPGAs 

package require -exact qsys 14.1

# module mp_txrx
set_module_property NAME mp_txrx
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Altera DSP Builder Advanced"
set_module_property DISPLAY_NAME mp_txrx
set_module_property EDITABLE false

# filesets
add_fileset DSPBA_QUARTUS_SYNTH QUARTUS_SYNTH quartus_synth_callback
set_fileset_property DSPBA_QUARTUS_SYNTH TOP_LEVEL mp_txrx

proc quartus_synth_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "mp_txrx.vhd" VHDL PATH "mp_txrx.vhd"
	add_fileset_file "mp_txrx_BER_Extraction.vhd" VHDL PATH "mp_txrx_BER_Extraction.vhd"
	add_fileset_file "mp_txrx_ChanView.vhd" VHDL PATH "mp_txrx_ChanView.vhd"
	add_fileset_file "mp_txrx_ChanView1.vhd" VHDL PATH "mp_txrx_ChanView1.vhd"
	add_fileset_file "mp_txrx_ChanView2.vhd" VHDL PATH "mp_txrx_ChanView2.vhd"
	add_fileset_file "mp_txrx_ChanView3.vhd" VHDL PATH "mp_txrx_ChanView3.vhd"
	add_fileset_file "mp_txrx_ChanView4.vhd" VHDL PATH "mp_txrx_ChanView4.vhd"
	add_fileset_file "mp_txrx_ChanView5.vhd" VHDL PATH "mp_txrx_ChanView5.vhd"
	add_fileset_file "mp_txrx_ChanView6.vhd" VHDL PATH "mp_txrx_ChanView6.vhd"
	add_fileset_file "mp_txrx_InterpolatingFIR.vhd" VHDL PATH "mp_txrx_InterpolatingFIR.vhd"
	add_fileset_file "mp_txrx_Memory.vhd" VHDL PATH "mp_txrx_Memory.vhd"
	add_fileset_file "mp_txrx_Memory_DualMem.hex" HEX PATH "mp_txrx_Memory_DualMem.hex"
	add_fileset_file "mp_txrx_Scale.vhd" VHDL PATH "mp_txrx_Scale.vhd"
	add_fileset_file "mp_txrx_Scale1.vhd" VHDL PATH "mp_txrx_Scale1.vhd"
	add_fileset_file "mp_txrx_Scale2_Q.vhd" VHDL PATH "mp_txrx_Scale2_Q.vhd"
	add_fileset_file "mp_txrx_Scale3_I.vhd" VHDL PATH "mp_txrx_Scale3_I.vhd"
	add_fileset_file "mp_txrx_Scrambled_shit_subsystem.vhd" VHDL PATH "mp_txrx_Scrambled_shit_subsystem.vhd"
	add_fileset_file "mp_txrx_SingleRateFIR1_Q.vhd" VHDL PATH "mp_txrx_SingleRateFIR1_Q.vhd"
	add_fileset_file "mp_txrx_SingleRateFIR1_Q_rm.hex" HEX PATH "mp_txrx_SingleRateFIR1_Q_rm.hex"
	add_fileset_file "mp_txrx_SingleRateFIR_I.vhd" VHDL PATH "mp_txrx_SingleRateFIR_I.vhd"
	add_fileset_file "mp_txrx_SingleRateFIR_I_rm.hex" HEX PATH "mp_txrx_SingleRateFIR_I_rm.hex"
	add_fileset_file "mp_txrx_Symbol_Recovery.vhd" VHDL PATH "mp_txrx_Symbol_Recovery.vhd"
}
add_fileset DSPBA_SIM_VERILOG SIM_VERILOG sim_verilog_callback
set_fileset_property DSPBA_SIM_VERILOG TOP_LEVEL mp_txrx

proc sim_verilog_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "mp_txrx.vhd" VHDL PATH "mp_txrx.vhd"
	add_fileset_file "mp_txrx_BER_Extraction.vhd" VHDL PATH "mp_txrx_BER_Extraction.vhd"
	add_fileset_file "mp_txrx_ChanView.vhd" VHDL PATH "mp_txrx_ChanView.vhd"
	add_fileset_file "mp_txrx_ChanView1.vhd" VHDL PATH "mp_txrx_ChanView1.vhd"
	add_fileset_file "mp_txrx_ChanView2.vhd" VHDL PATH "mp_txrx_ChanView2.vhd"
	add_fileset_file "mp_txrx_ChanView3.vhd" VHDL PATH "mp_txrx_ChanView3.vhd"
	add_fileset_file "mp_txrx_ChanView4.vhd" VHDL PATH "mp_txrx_ChanView4.vhd"
	add_fileset_file "mp_txrx_ChanView5.vhd" VHDL PATH "mp_txrx_ChanView5.vhd"
	add_fileset_file "mp_txrx_ChanView6.vhd" VHDL PATH "mp_txrx_ChanView6.vhd"
	add_fileset_file "mp_txrx_InterpolatingFIR.vhd" VHDL PATH "mp_txrx_InterpolatingFIR.vhd"
	add_fileset_file "mp_txrx_Memory.vhd" VHDL PATH "mp_txrx_Memory.vhd"
	add_fileset_file "mp_txrx_Memory_DualMem.hex" HEX PATH "mp_txrx_Memory_DualMem.hex"
	add_fileset_file "mp_txrx_Scale.vhd" VHDL PATH "mp_txrx_Scale.vhd"
	add_fileset_file "mp_txrx_Scale1.vhd" VHDL PATH "mp_txrx_Scale1.vhd"
	add_fileset_file "mp_txrx_Scale2_Q.vhd" VHDL PATH "mp_txrx_Scale2_Q.vhd"
	add_fileset_file "mp_txrx_Scale3_I.vhd" VHDL PATH "mp_txrx_Scale3_I.vhd"
	add_fileset_file "mp_txrx_Scrambled_shit_subsystem.vhd" VHDL PATH "mp_txrx_Scrambled_shit_subsystem.vhd"
	add_fileset_file "mp_txrx_SingleRateFIR1_Q.vhd" VHDL PATH "mp_txrx_SingleRateFIR1_Q.vhd"
	add_fileset_file "mp_txrx_SingleRateFIR1_Q_rm.hex" HEX PATH "mp_txrx_SingleRateFIR1_Q_rm.hex"
	add_fileset_file "mp_txrx_SingleRateFIR_I.vhd" VHDL PATH "mp_txrx_SingleRateFIR_I.vhd"
	add_fileset_file "mp_txrx_SingleRateFIR_I_rm.hex" HEX PATH "mp_txrx_SingleRateFIR_I_rm.hex"
	add_fileset_file "mp_txrx_Symbol_Recovery.vhd" VHDL PATH "mp_txrx_Symbol_Recovery.vhd"
}
add_fileset DSPBA_SIM_VHDL SIM_VHDL sim_vhdl_callback
set_fileset_property DSPBA_SIM_VHDL TOP_LEVEL mp_txrx

proc sim_vhdl_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "mp_txrx.vhd" VHDL PATH "mp_txrx.vhd"
	add_fileset_file "mp_txrx_BER_Extraction.vhd" VHDL PATH "mp_txrx_BER_Extraction.vhd"
	add_fileset_file "mp_txrx_ChanView.vhd" VHDL PATH "mp_txrx_ChanView.vhd"
	add_fileset_file "mp_txrx_ChanView1.vhd" VHDL PATH "mp_txrx_ChanView1.vhd"
	add_fileset_file "mp_txrx_ChanView2.vhd" VHDL PATH "mp_txrx_ChanView2.vhd"
	add_fileset_file "mp_txrx_ChanView3.vhd" VHDL PATH "mp_txrx_ChanView3.vhd"
	add_fileset_file "mp_txrx_ChanView4.vhd" VHDL PATH "mp_txrx_ChanView4.vhd"
	add_fileset_file "mp_txrx_ChanView5.vhd" VHDL PATH "mp_txrx_ChanView5.vhd"
	add_fileset_file "mp_txrx_ChanView6.vhd" VHDL PATH "mp_txrx_ChanView6.vhd"
	add_fileset_file "mp_txrx_InterpolatingFIR.vhd" VHDL PATH "mp_txrx_InterpolatingFIR.vhd"
	add_fileset_file "mp_txrx_Memory.vhd" VHDL PATH "mp_txrx_Memory.vhd"
	add_fileset_file "mp_txrx_Memory_DualMem.hex" HEX PATH "mp_txrx_Memory_DualMem.hex"
	add_fileset_file "mp_txrx_Scale.vhd" VHDL PATH "mp_txrx_Scale.vhd"
	add_fileset_file "mp_txrx_Scale1.vhd" VHDL PATH "mp_txrx_Scale1.vhd"
	add_fileset_file "mp_txrx_Scale2_Q.vhd" VHDL PATH "mp_txrx_Scale2_Q.vhd"
	add_fileset_file "mp_txrx_Scale3_I.vhd" VHDL PATH "mp_txrx_Scale3_I.vhd"
	add_fileset_file "mp_txrx_Scrambled_shit_subsystem.vhd" VHDL PATH "mp_txrx_Scrambled_shit_subsystem.vhd"
	add_fileset_file "mp_txrx_SingleRateFIR1_Q.vhd" VHDL PATH "mp_txrx_SingleRateFIR1_Q.vhd"
	add_fileset_file "mp_txrx_SingleRateFIR1_Q_rm.hex" HEX PATH "mp_txrx_SingleRateFIR1_Q_rm.hex"
	add_fileset_file "mp_txrx_SingleRateFIR_I.vhd" VHDL PATH "mp_txrx_SingleRateFIR_I.vhd"
	add_fileset_file "mp_txrx_SingleRateFIR_I_rm.hex" HEX PATH "mp_txrx_SingleRateFIR_I_rm.hex"
	add_fileset_file "mp_txrx_Symbol_Recovery.vhd" VHDL PATH "mp_txrx_Symbol_Recovery.vhd"
}

# interfaces
# Interface clock
add_interface clock clock end
set_interface_property clock ENABLED true
add_interface_port clock clk clk Input 1
add_interface_port clock areset reset Input 1

# Interface bus_reset
add_interface bus_reset reset end
set_interface_property bus_reset ENABLED true
set_interface_property bus_reset ASSOCIATED_CLOCK clock
add_interface_port bus_reset h_areset reset Input 1

# Interface bus
add_interface bus avalon slave
set_interface_property bus maximumPendingReadTransactions 4
set_interface_property bus setupTime 0
set_interface_property bus ASSOCIATED_CLOCK clock
set_interface_property bus ENABLED true
add_interface_port bus busIn_address address Input 10
add_interface_port bus busIn_read read Input 1
set_port_property busIn_read VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port bus busIn_write write Input 1
set_port_property busIn_write VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port bus busIn_writedata writedata Input 16
add_interface_port bus busOut_readdata readdata Output 16
add_interface_port bus busOut_readdatavalid readdatavalid Output 1
set_port_property busOut_readdatavalid VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port bus busOut_waitrequest waitrequest Output 1
set_port_property busOut_waitrequest VHDL_TYPE STD_LOGIC_VECTOR

# Interface exp
add_interface exp conduit end
set_interface_property exp ENABLED true
add_interface_port exp fromADC_I data_fromADC_I Input 12
add_interface_port exp fromADC_Q data_fromADC_Q Input 12
add_interface_port exp sym_phase data_sym_phase Output 28
add_interface_port exp BER data_BER Output 1
set_port_property BER VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port exp bit_error data_bit_error Output 1
set_port_property bit_error VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port exp sym_pwr data_sym_pwr Output 12
